# Create simple front-end node
pp01:
  hostname: web.ps
  container_name: web.ps
  image: ps-tomcat-base
  ports:
    - "8020:8080"
    - "8000:8000"
  volumes:
    - ./files/tomcat-website/server.xml:/usr/local/tomcat/conf/server.xml
    - ./files/tomcat-website/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./logs/web:/usr/local/tomcat/logs
#    - /home/limpygnome/git-remote/project-sandbox/components/website/target/website-1.0:/usr/local/tomcat/webapps/website
    - ./../website/target/projectsandbox-website-1.0.war:/usr/local/tomcat/webapps/website.war
